# docker-compose.yml
version: "3.8"

services:
  storage:
    image: redis

  counter:
    build: .
    ports:
      - 80:3000
    environment:
      PORT: 3000
      STORAGE_URL: storage
    depends_on:
      - storage
