# docker-compose.yml
version: "3.8"

services:
  counter:
    build: .
    restart: always
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DATA_FOLDER: storage
    volumes:
      - C:\counter-storage:/app/storage
